
package server.coordination;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CoordinationServiceImplService", targetNamespace = "http://coordination.server/")
public class CoordinationServiceImplService
    extends Service
{

    private final static URL COORDINATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COORDINATIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName COORDINATIONSERVICEIMPLSERVICE_QNAME = new QName("http://coordination.server/", "CoordinationServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9085/CoordinationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COORDINATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        COORDINATIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CoordinationServiceImplService() {
        super(__getWsdlLocation(), COORDINATIONSERVICEIMPLSERVICE_QNAME);
    }

    public CoordinationServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COORDINATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public CoordinationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, COORDINATIONSERVICEIMPLSERVICE_QNAME);
    }

    public CoordinationServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COORDINATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public CoordinationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CoordinationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CoordinationService
     */
    @WebEndpoint(name = "CoordinationServiceImplPort")
    public CoordinationService getCoordinationServiceImplPort() {
        return super.getPort(new QName("http://coordination.server/", "CoordinationServiceImplPort"), CoordinationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoordinationService
     */
    @WebEndpoint(name = "CoordinationServiceImplPort")
    public CoordinationService getCoordinationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://coordination.server/", "CoordinationServiceImplPort"), CoordinationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COORDINATIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw COORDINATIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return COORDINATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
