
package server.coordination;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;
import java.util.concurrent.Future;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CoordinationService", targetNamespace = "http://coordination.server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CoordinationService {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<server.coordination.CommitResponse>
     */
    @WebMethod(operationName = "commit")
    @RequestWrapper(localName = "commit", targetNamespace = "http://coordination.server/", className = "server.coordination.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.CommitResponse")
    public Response<CommitResponse> commitAsync(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "commit")
    @RequestWrapper(localName = "commit", targetNamespace = "http://coordination.server/", className = "server.coordination.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.CommitResponse")
    public Future<?> commitAsync(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "asyncHandler", targetNamespace = "")
            AsyncHandler<CommitResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns server.coordination.ServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commit", targetNamespace = "http://coordination.server/", className = "server.coordination.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.CommitResponse")
    public ServiceResponse commit(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<server.coordination.AbortResponse>
     */
    @WebMethod(operationName = "abort")
    @RequestWrapper(localName = "abort", targetNamespace = "http://coordination.server/", className = "server.coordination.Abort")
    @ResponseWrapper(localName = "abortResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.AbortResponse")
    public Response<AbortResponse> abortAsync(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "abort")
    @RequestWrapper(localName = "abort", targetNamespace = "http://coordination.server/", className = "server.coordination.Abort")
    @ResponseWrapper(localName = "abortResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.AbortResponse")
    public Future<?> abortAsync(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "asyncHandler", targetNamespace = "")
            AsyncHandler<AbortResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns server.coordination.ServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "abort", targetNamespace = "http://coordination.server/", className = "server.coordination.Abort")
    @ResponseWrapper(localName = "abortResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.AbortResponse")
    public ServiceResponse abort(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<server.coordination.RollbackResponse>
     */
    @WebMethod(operationName = "rollback")
    @RequestWrapper(localName = "rollback", targetNamespace = "http://coordination.server/", className = "server.coordination.Rollback")
    @ResponseWrapper(localName = "rollbackResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.RollbackResponse")
    public Response<RollbackResponse> rollbackAsync(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "rollback")
    @RequestWrapper(localName = "rollback", targetNamespace = "http://coordination.server/", className = "server.coordination.Rollback")
    @ResponseWrapper(localName = "rollbackResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.RollbackResponse")
    public Future<?> rollbackAsync(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "asyncHandler", targetNamespace = "")
            AsyncHandler<RollbackResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns server.coordination.ServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rollback", targetNamespace = "http://coordination.server/", className = "server.coordination.Rollback")
    @ResponseWrapper(localName = "rollbackResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.RollbackResponse")
    public ServiceResponse rollback(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<server.coordination.PrepareResponse>
     */
    @WebMethod(operationName = "prepare")
    @RequestWrapper(localName = "prepare", targetNamespace = "http://coordination.server/", className = "server.coordination.Prepare")
    @ResponseWrapper(localName = "prepareResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.PrepareResponse")
    public Response<PrepareResponse> prepareAsync(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "prepare")
    @RequestWrapper(localName = "prepare", targetNamespace = "http://coordination.server/", className = "server.coordination.Prepare")
    @ResponseWrapper(localName = "prepareResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.PrepareResponse")
    public Future<?> prepareAsync(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "asyncHandler", targetNamespace = "")
            AsyncHandler<PrepareResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns server.coordination.ServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prepare", targetNamespace = "http://coordination.server/", className = "server.coordination.Prepare")
    @ResponseWrapper(localName = "prepareResponse", targetNamespace = "http://coordination.server/", className = "server.coordination.PrepareResponse")
    public ServiceResponse prepare(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

}
