/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thriftgen.registration;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;

import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.Collections;

public class EndPointReference implements org.apache.thrift.TBase<EndPointReference, EndPointReference._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EndPointReference");

  private static final org.apache.thrift.protocol.TField ADDRESS_FIELD_DESC = new org.apache.thrift.protocol.TField("address", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PRIVATE_INSTANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("privateInstance", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EndPointReferenceStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EndPointReferenceTupleSchemeFactory());
  }

  public String address; // required
  public int privateInstance; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ADDRESS((short)1, "address"),
    PRIVATE_INSTANCE((short)2, "privateInstance");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ADDRESS
          return ADDRESS;
        case 2: // PRIVATE_INSTANCE
          return PRIVATE_INSTANCE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PRIVATEINSTANCE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ADDRESS, new org.apache.thrift.meta_data.FieldMetaData("address", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRIVATE_INSTANCE, new org.apache.thrift.meta_data.FieldMetaData("privateInstance", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EndPointReference.class, metaDataMap);
  }

  public EndPointReference() {
  }

  public EndPointReference(
    String address,
    int privateInstance)
  {
    this();
    this.address = address;
    this.privateInstance = privateInstance;
    setPrivateInstanceIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EndPointReference(EndPointReference other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetAddress()) {
      this.address = other.address;
    }
    this.privateInstance = other.privateInstance;
  }

  public EndPointReference deepCopy() {
    return new EndPointReference(this);
  }

  @Override
  public void clear() {
    this.address = null;
    setPrivateInstanceIsSet(false);
    this.privateInstance = 0;
  }

  public String getAddress() {
    return this.address;
  }

  public EndPointReference setAddress(String address) {
    this.address = address;
    return this;
  }

  public void unsetAddress() {
    this.address = null;
  }

  /** Returns true if field address is set (has been assigned a value) and false otherwise */
  public boolean isSetAddress() {
    return this.address != null;
  }

  public void setAddressIsSet(boolean value) {
    if (!value) {
      this.address = null;
    }
  }

  public int getPrivateInstance() {
    return this.privateInstance;
  }

  public EndPointReference setPrivateInstance(int privateInstance) {
    this.privateInstance = privateInstance;
    setPrivateInstanceIsSet(true);
    return this;
  }

  public void unsetPrivateInstance() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PRIVATEINSTANCE_ISSET_ID);
  }

  /** Returns true if field privateInstance is set (has been assigned a value) and false otherwise */
  public boolean isSetPrivateInstance() {
    return EncodingUtils.testBit(__isset_bitfield, __PRIVATEINSTANCE_ISSET_ID);
  }

  public void setPrivateInstanceIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PRIVATEINSTANCE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ADDRESS:
      if (value == null) {
        unsetAddress();
      } else {
        setAddress((String)value);
      }
      break;

    case PRIVATE_INSTANCE:
      if (value == null) {
        unsetPrivateInstance();
      } else {
        setPrivateInstance((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ADDRESS:
      return getAddress();

    case PRIVATE_INSTANCE:
      return Integer.valueOf(getPrivateInstance());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ADDRESS:
      return isSetAddress();
    case PRIVATE_INSTANCE:
      return isSetPrivateInstance();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EndPointReference)
      return this.equals((EndPointReference)that);
    return false;
  }

  public boolean equals(EndPointReference that) {
    if (that == null)
      return false;

    boolean this_present_address = true && this.isSetAddress();
    boolean that_present_address = true && that.isSetAddress();
    if (this_present_address || that_present_address) {
      if (!(this_present_address && that_present_address))
        return false;
      if (!this.address.equals(that.address))
        return false;
    }

    boolean this_present_privateInstance = true;
    boolean that_present_privateInstance = true;
    if (this_present_privateInstance || that_present_privateInstance) {
      if (!(this_present_privateInstance && that_present_privateInstance))
        return false;
      if (this.privateInstance != that.privateInstance)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(EndPointReference other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    EndPointReference typedOther = (EndPointReference)other;

    lastComparison = Boolean.valueOf(isSetAddress()).compareTo(typedOther.isSetAddress());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAddress()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.address, typedOther.address);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPrivateInstance()).compareTo(typedOther.isSetPrivateInstance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrivateInstance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.privateInstance, typedOther.privateInstance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("EndPointReference(");
    boolean first = true;

    sb.append("address:");
    if (this.address == null) {
      sb.append("null");
    } else {
      sb.append(this.address);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("privateInstance:");
    sb.append(this.privateInstance);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    if (address == null) {
      throw new TProtocolException("Required field 'address' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'privateInstance' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EndPointReferenceStandardSchemeFactory implements SchemeFactory {
    public EndPointReferenceStandardScheme getScheme() {
      return new EndPointReferenceStandardScheme();
    }
  }

  private static class EndPointReferenceStandardScheme extends StandardScheme<EndPointReference> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, EndPointReference struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ADDRESS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.address = iprot.readString();
              struct.setAddressIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PRIVATE_INSTANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.privateInstance = iprot.readI32();
              struct.setPrivateInstanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetPrivateInstance()) {
        throw new TProtocolException("Required field 'privateInstance' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, EndPointReference struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.address != null) {
        oprot.writeFieldBegin(ADDRESS_FIELD_DESC);
        oprot.writeString(struct.address);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PRIVATE_INSTANCE_FIELD_DESC);
      oprot.writeI32(struct.privateInstance);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EndPointReferenceTupleSchemeFactory implements SchemeFactory {
    public EndPointReferenceTupleScheme getScheme() {
      return new EndPointReferenceTupleScheme();
    }
  }

  private static class EndPointReferenceTupleScheme extends TupleScheme<EndPointReference> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EndPointReference struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.address);
      oprot.writeI32(struct.privateInstance);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EndPointReference struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.address = iprot.readString();
      struct.setAddressIsSet(true);
      struct.privateInstance = iprot.readI32();
      struct.setPrivateInstanceIsSet(true);
    }
  }

}

