/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thriftgen.registration;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;

import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RegistrationService {

  public interface Iface {

    public boolean registerParticipant(CoordinationContext coorContext, String protocolIdentifier, EndPointReference participantEPR) throws TException;

  }

  public interface AsyncIface {

    public void registerParticipant(CoordinationContext coorContext, String protocolIdentifier, EndPointReference participantEPR, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.registerParticipant_call> resultHandler) throws TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public boolean registerParticipant(CoordinationContext coorContext, String protocolIdentifier, EndPointReference participantEPR) throws TException
    {
      send_registerParticipant(coorContext, protocolIdentifier, participantEPR);
      return recv_registerParticipant();
    }

    public void send_registerParticipant(CoordinationContext coorContext, String protocolIdentifier, EndPointReference participantEPR) throws TException
    {
      registerParticipant_args args = new registerParticipant_args();
      args.setCoorContext(coorContext);
      args.setProtocolIdentifier(protocolIdentifier);
      args.setParticipantEPR(participantEPR);
      sendBase("registerParticipant", args);
    }

    public boolean recv_registerParticipant() throws TException
    {
      registerParticipant_result result = new registerParticipant_result();
      receiveBase(result, "registerParticipant");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "registerParticipant failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void registerParticipant(CoordinationContext coorContext, String protocolIdentifier, EndPointReference participantEPR, org.apache.thrift.async.AsyncMethodCallback<registerParticipant_call> resultHandler) throws TException {
      checkReady();
      registerParticipant_call method_call = new registerParticipant_call(coorContext, protocolIdentifier, participantEPR, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class registerParticipant_call extends org.apache.thrift.async.TAsyncMethodCall {
      private CoordinationContext coorContext;
      private String protocolIdentifier;
      private EndPointReference participantEPR;
      public registerParticipant_call(CoordinationContext coorContext, String protocolIdentifier, EndPointReference participantEPR, org.apache.thrift.async.AsyncMethodCallback<registerParticipant_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.coorContext = coorContext;
        this.protocolIdentifier = protocolIdentifier;
        this.participantEPR = participantEPR;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("registerParticipant", org.apache.thrift.protocol.TMessageType.CALL, 0));
        registerParticipant_args args = new registerParticipant_args();
        args.setCoorContext(coorContext);
        args.setProtocolIdentifier(protocolIdentifier);
        args.setParticipantEPR(participantEPR);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public boolean getResult() throws TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_registerParticipant();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("registerParticipant", new registerParticipant());
      return processMap;
    }

    public static class registerParticipant<I extends Iface> extends org.apache.thrift.ProcessFunction<I, registerParticipant_args> {
      public registerParticipant() {
        super("registerParticipant");
      }

      public registerParticipant_args getEmptyArgsInstance() {
        return new registerParticipant_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public registerParticipant_result getResult(I iface, registerParticipant_args args) throws TException {
        registerParticipant_result result = new registerParticipant_result();
        result.success = iface.registerParticipant(args.coorContext, args.protocolIdentifier, args.participantEPR);
        result.setSuccessIsSet(true);
        return result;
      }
    }

  }

  public static class registerParticipant_args implements org.apache.thrift.TBase<registerParticipant_args, registerParticipant_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("registerParticipant_args");

    private static final org.apache.thrift.protocol.TField COOR_CONTEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("coorContext", org.apache.thrift.protocol.TType.STRUCT, (short)1);
    private static final org.apache.thrift.protocol.TField PROTOCOL_IDENTIFIER_FIELD_DESC = new org.apache.thrift.protocol.TField("protocolIdentifier", org.apache.thrift.protocol.TType.STRING, (short)2);
    private static final org.apache.thrift.protocol.TField PARTICIPANT_EPR_FIELD_DESC = new org.apache.thrift.protocol.TField("participantEPR", org.apache.thrift.protocol.TType.STRUCT, (short)3);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new registerParticipant_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new registerParticipant_argsTupleSchemeFactory());
    }

    public CoordinationContext coorContext; // required
    public String protocolIdentifier; // required
    public EndPointReference participantEPR; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      COOR_CONTEXT((short)1, "coorContext"),
      PROTOCOL_IDENTIFIER((short)2, "protocolIdentifier"),
      PARTICIPANT_EPR((short)3, "participantEPR");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // COOR_CONTEXT
            return COOR_CONTEXT;
          case 2: // PROTOCOL_IDENTIFIER
            return PROTOCOL_IDENTIFIER;
          case 3: // PARTICIPANT_EPR
            return PARTICIPANT_EPR;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.COOR_CONTEXT, new org.apache.thrift.meta_data.FieldMetaData("coorContext", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CoordinationContext.class)));
      tmpMap.put(_Fields.PROTOCOL_IDENTIFIER, new org.apache.thrift.meta_data.FieldMetaData("protocolIdentifier", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.PARTICIPANT_EPR, new org.apache.thrift.meta_data.FieldMetaData("participantEPR", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EndPointReference.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(registerParticipant_args.class, metaDataMap);
    }

    public registerParticipant_args() {
    }

    public registerParticipant_args(
      CoordinationContext coorContext,
      String protocolIdentifier,
      EndPointReference participantEPR)
    {
      this();
      this.coorContext = coorContext;
      this.protocolIdentifier = protocolIdentifier;
      this.participantEPR = participantEPR;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public registerParticipant_args(registerParticipant_args other) {
      if (other.isSetCoorContext()) {
        this.coorContext = new CoordinationContext(other.coorContext);
      }
      if (other.isSetProtocolIdentifier()) {
        this.protocolIdentifier = other.protocolIdentifier;
      }
      if (other.isSetParticipantEPR()) {
        this.participantEPR = new EndPointReference(other.participantEPR);
      }
    }

    public registerParticipant_args deepCopy() {
      return new registerParticipant_args(this);
    }

    @Override
    public void clear() {
      this.coorContext = null;
      this.protocolIdentifier = null;
      this.participantEPR = null;
    }

    public CoordinationContext getCoorContext() {
      return this.coorContext;
    }

    public registerParticipant_args setCoorContext(CoordinationContext coorContext) {
      this.coorContext = coorContext;
      return this;
    }

    public void unsetCoorContext() {
      this.coorContext = null;
    }

    /** Returns true if field coorContext is set (has been assigned a value) and false otherwise */
    public boolean isSetCoorContext() {
      return this.coorContext != null;
    }

    public void setCoorContextIsSet(boolean value) {
      if (!value) {
        this.coorContext = null;
      }
    }

    public String getProtocolIdentifier() {
      return this.protocolIdentifier;
    }

    public registerParticipant_args setProtocolIdentifier(String protocolIdentifier) {
      this.protocolIdentifier = protocolIdentifier;
      return this;
    }

    public void unsetProtocolIdentifier() {
      this.protocolIdentifier = null;
    }

    /** Returns true if field protocolIdentifier is set (has been assigned a value) and false otherwise */
    public boolean isSetProtocolIdentifier() {
      return this.protocolIdentifier != null;
    }

    public void setProtocolIdentifierIsSet(boolean value) {
      if (!value) {
        this.protocolIdentifier = null;
      }
    }

    public EndPointReference getParticipantEPR() {
      return this.participantEPR;
    }

    public registerParticipant_args setParticipantEPR(EndPointReference participantEPR) {
      this.participantEPR = participantEPR;
      return this;
    }

    public void unsetParticipantEPR() {
      this.participantEPR = null;
    }

    /** Returns true if field participantEPR is set (has been assigned a value) and false otherwise */
    public boolean isSetParticipantEPR() {
      return this.participantEPR != null;
    }

    public void setParticipantEPRIsSet(boolean value) {
      if (!value) {
        this.participantEPR = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case COOR_CONTEXT:
        if (value == null) {
          unsetCoorContext();
        } else {
          setCoorContext((CoordinationContext)value);
        }
        break;

      case PROTOCOL_IDENTIFIER:
        if (value == null) {
          unsetProtocolIdentifier();
        } else {
          setProtocolIdentifier((String)value);
        }
        break;

      case PARTICIPANT_EPR:
        if (value == null) {
          unsetParticipantEPR();
        } else {
          setParticipantEPR((EndPointReference)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case COOR_CONTEXT:
        return getCoorContext();

      case PROTOCOL_IDENTIFIER:
        return getProtocolIdentifier();

      case PARTICIPANT_EPR:
        return getParticipantEPR();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case COOR_CONTEXT:
        return isSetCoorContext();
      case PROTOCOL_IDENTIFIER:
        return isSetProtocolIdentifier();
      case PARTICIPANT_EPR:
        return isSetParticipantEPR();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof registerParticipant_args)
        return this.equals((registerParticipant_args)that);
      return false;
    }

    public boolean equals(registerParticipant_args that) {
      if (that == null)
        return false;

      boolean this_present_coorContext = true && this.isSetCoorContext();
      boolean that_present_coorContext = true && that.isSetCoorContext();
      if (this_present_coorContext || that_present_coorContext) {
        if (!(this_present_coorContext && that_present_coorContext))
          return false;
        if (!this.coorContext.equals(that.coorContext))
          return false;
      }

      boolean this_present_protocolIdentifier = true && this.isSetProtocolIdentifier();
      boolean that_present_protocolIdentifier = true && that.isSetProtocolIdentifier();
      if (this_present_protocolIdentifier || that_present_protocolIdentifier) {
        if (!(this_present_protocolIdentifier && that_present_protocolIdentifier))
          return false;
        if (!this.protocolIdentifier.equals(that.protocolIdentifier))
          return false;
      }

      boolean this_present_participantEPR = true && this.isSetParticipantEPR();
      boolean that_present_participantEPR = true && that.isSetParticipantEPR();
      if (this_present_participantEPR || that_present_participantEPR) {
        if (!(this_present_participantEPR && that_present_participantEPR))
          return false;
        if (!this.participantEPR.equals(that.participantEPR))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(registerParticipant_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      registerParticipant_args typedOther = (registerParticipant_args)other;

      lastComparison = Boolean.valueOf(isSetCoorContext()).compareTo(typedOther.isSetCoorContext());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetCoorContext()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.coorContext, typedOther.coorContext);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetProtocolIdentifier()).compareTo(typedOther.isSetProtocolIdentifier());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetProtocolIdentifier()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.protocolIdentifier, typedOther.protocolIdentifier);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetParticipantEPR()).compareTo(typedOther.isSetParticipantEPR());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetParticipantEPR()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.participantEPR, typedOther.participantEPR);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("registerParticipant_args(");
      boolean first = true;

      sb.append("coorContext:");
      if (this.coorContext == null) {
        sb.append("null");
      } else {
        sb.append(this.coorContext);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("protocolIdentifier:");
      if (this.protocolIdentifier == null) {
        sb.append("null");
      } else {
        sb.append(this.protocolIdentifier);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("participantEPR:");
      if (this.participantEPR == null) {
        sb.append("null");
      } else {
        sb.append(this.participantEPR);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
      if (coorContext != null) {
        coorContext.validate();
      }
      if (participantEPR != null) {
        participantEPR.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class registerParticipant_argsStandardSchemeFactory implements SchemeFactory {
      public registerParticipant_argsStandardScheme getScheme() {
        return new registerParticipant_argsStandardScheme();
      }
    }

    private static class registerParticipant_argsStandardScheme extends StandardScheme<registerParticipant_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, registerParticipant_args struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // COOR_CONTEXT
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.coorContext = new CoordinationContext();
                struct.coorContext.read(iprot);
                struct.setCoorContextIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // PROTOCOL_IDENTIFIER
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.protocolIdentifier = iprot.readString();
                struct.setProtocolIdentifierIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // PARTICIPANT_EPR
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.participantEPR = new EndPointReference();
                struct.participantEPR.read(iprot);
                struct.setParticipantEPRIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, registerParticipant_args struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.coorContext != null) {
          oprot.writeFieldBegin(COOR_CONTEXT_FIELD_DESC);
          struct.coorContext.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.protocolIdentifier != null) {
          oprot.writeFieldBegin(PROTOCOL_IDENTIFIER_FIELD_DESC);
          oprot.writeString(struct.protocolIdentifier);
          oprot.writeFieldEnd();
        }
        if (struct.participantEPR != null) {
          oprot.writeFieldBegin(PARTICIPANT_EPR_FIELD_DESC);
          struct.participantEPR.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class registerParticipant_argsTupleSchemeFactory implements SchemeFactory {
      public registerParticipant_argsTupleScheme getScheme() {
        return new registerParticipant_argsTupleScheme();
      }
    }

    private static class registerParticipant_argsTupleScheme extends TupleScheme<registerParticipant_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, registerParticipant_args struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetCoorContext()) {
          optionals.set(0);
        }
        if (struct.isSetProtocolIdentifier()) {
          optionals.set(1);
        }
        if (struct.isSetParticipantEPR()) {
          optionals.set(2);
        }
        oprot.writeBitSet(optionals, 3);
        if (struct.isSetCoorContext()) {
          struct.coorContext.write(oprot);
        }
        if (struct.isSetProtocolIdentifier()) {
          oprot.writeString(struct.protocolIdentifier);
        }
        if (struct.isSetParticipantEPR()) {
          struct.participantEPR.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, registerParticipant_args struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.coorContext = new CoordinationContext();
          struct.coorContext.read(iprot);
          struct.setCoorContextIsSet(true);
        }
        if (incoming.get(1)) {
          struct.protocolIdentifier = iprot.readString();
          struct.setProtocolIdentifierIsSet(true);
        }
        if (incoming.get(2)) {
          struct.participantEPR = new EndPointReference();
          struct.participantEPR.read(iprot);
          struct.setParticipantEPRIsSet(true);
        }
      }
    }

  }

  public static class registerParticipant_result implements org.apache.thrift.TBase<registerParticipant_result, registerParticipant_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("registerParticipant_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.BOOL, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new registerParticipant_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new registerParticipant_resultTupleSchemeFactory());
    }

    public boolean success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __SUCCESS_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(registerParticipant_result.class, metaDataMap);
    }

    public registerParticipant_result() {
    }

    public registerParticipant_result(
      boolean success)
    {
      this();
      this.success = success;
      setSuccessIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public registerParticipant_result(registerParticipant_result other) {
      __isset_bitfield = other.__isset_bitfield;
      this.success = other.success;
    }

    public registerParticipant_result deepCopy() {
      return new registerParticipant_result(this);
    }

    @Override
    public void clear() {
      setSuccessIsSet(false);
      this.success = false;
    }

    public boolean isSuccess() {
      return this.success;
    }

    public registerParticipant_result setSuccess(boolean success) {
      this.success = success;
      setSuccessIsSet(true);
      return this;
    }

    public void unsetSuccess() {
      __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SUCCESS_ISSET_ID);
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return EncodingUtils.testBit(__isset_bitfield, __SUCCESS_ISSET_ID);
    }

    public void setSuccessIsSet(boolean value) {
      __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SUCCESS_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((Boolean)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return Boolean.valueOf(isSuccess());

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof registerParticipant_result)
        return this.equals((registerParticipant_result)that);
      return false;
    }

    public boolean equals(registerParticipant_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true;
      boolean that_present_success = true;
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (this.success != that.success)
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(registerParticipant_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      registerParticipant_result typedOther = (registerParticipant_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("registerParticipant_result(");
      boolean first = true;

      sb.append("success:");
      sb.append(this.success);
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class registerParticipant_resultStandardSchemeFactory implements SchemeFactory {
      public registerParticipant_resultStandardScheme getScheme() {
        return new registerParticipant_resultStandardScheme();
      }
    }

    private static class registerParticipant_resultStandardScheme extends StandardScheme<registerParticipant_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, registerParticipant_result struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
                struct.success = iprot.readBool();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, registerParticipant_result struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.isSetSuccess()) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeBool(struct.success);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class registerParticipant_resultTupleSchemeFactory implements SchemeFactory {
      public registerParticipant_resultTupleScheme getScheme() {
        return new registerParticipant_resultTupleScheme();
      }
    }

    private static class registerParticipant_resultTupleScheme extends TupleScheme<registerParticipant_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, registerParticipant_result struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          oprot.writeBool(struct.success);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, registerParticipant_result struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = iprot.readBool();
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
